// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: actual_lrp.proto

package models

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ActualLRPNetInfo_PreferredAddress int32

const (
	ActualLRPNetInfo_PreferredAddressUnknown  ActualLRPNetInfo_PreferredAddress = 0
	ActualLRPNetInfo_PreferredAddressInstance ActualLRPNetInfo_PreferredAddress = 1
	ActualLRPNetInfo_PreferredAddressHost     ActualLRPNetInfo_PreferredAddress = 2
)

var ActualLRPNetInfo_PreferredAddress_name = map[int32]string{
	0: "UNKNOWN",
	1: "INSTANCE",
	2: "HOST",
}

var ActualLRPNetInfo_PreferredAddress_value = map[string]int32{
	"UNKNOWN":  0,
	"INSTANCE": 1,
	"HOST":     2,
}

func (ActualLRPNetInfo_PreferredAddress) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{4, 0}
}

type ActualLRP_Presence int32

const (
	ActualLRP_Ordinary   ActualLRP_Presence = 0
	ActualLRP_Evacuating ActualLRP_Presence = 1
	ActualLRP_Suspect    ActualLRP_Presence = 2
)

var ActualLRP_Presence_name = map[int32]string{
	0: "ORDINARY",
	1: "EVACUATING",
	2: "SUSPECT",
}

var ActualLRP_Presence_value = map[string]int32{
	"ORDINARY":   0,
	"EVACUATING": 1,
	"SUSPECT":    2,
}

func (ActualLRP_Presence) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{6, 0}
}

// Deprecated: Do not use.
type ActualLRPGroup struct {
	Instance   *ActualLRP `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Evacuating *ActualLRP `protobuf:"bytes,2,opt,name=evacuating,proto3" json:"evacuating,omitempty"`
}

func (m *ActualLRPGroup) Reset()      { *m = ActualLRPGroup{} }
func (*ActualLRPGroup) ProtoMessage() {}
func (*ActualLRPGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{0}
}
func (m *ActualLRPGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRPGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRPGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRPGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRPGroup.Merge(m, src)
}
func (m *ActualLRPGroup) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRPGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRPGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRPGroup proto.InternalMessageInfo

func (m *ActualLRPGroup) GetInstance() *ActualLRP {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *ActualLRPGroup) GetEvacuating() *ActualLRP {
	if m != nil {
		return m.Evacuating
	}
	return nil
}

type PortMapping struct {
	ContainerPort         uint32 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port"`
	HostPort              uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port"`
	ContainerTlsProxyPort uint32 `protobuf:"varint,3,opt,name=container_tls_proxy_port,json=containerTlsProxyPort,proto3" json:"container_tls_proxy_port"`
	HostTlsProxyPort      uint32 `protobuf:"varint,4,opt,name=host_tls_proxy_port,json=hostTlsProxyPort,proto3" json:"host_tls_proxy_port"`
}

func (m *PortMapping) Reset()      { *m = PortMapping{} }
func (*PortMapping) ProtoMessage() {}
func (*PortMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{1}
}
func (m *PortMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PortMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PortMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PortMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortMapping.Merge(m, src)
}
func (m *PortMapping) XXX_Size() int {
	return m.Size()
}
func (m *PortMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_PortMapping.DiscardUnknown(m)
}

var xxx_messageInfo_PortMapping proto.InternalMessageInfo

func (m *PortMapping) GetContainerPort() uint32 {
	if m != nil {
		return m.ContainerPort
	}
	return 0
}

func (m *PortMapping) GetHostPort() uint32 {
	if m != nil {
		return m.HostPort
	}
	return 0
}

func (m *PortMapping) GetContainerTlsProxyPort() uint32 {
	if m != nil {
		return m.ContainerTlsProxyPort
	}
	return 0
}

func (m *PortMapping) GetHostTlsProxyPort() uint32 {
	if m != nil {
		return m.HostTlsProxyPort
	}
	return 0
}

type ActualLRPKey struct {
	ProcessGuid string `protobuf:"bytes,1,opt,name=process_guid,json=processGuid,proto3" json:"process_guid"`
	Index       int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index"`
	Domain      string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain"`
}

func (m *ActualLRPKey) Reset()      { *m = ActualLRPKey{} }
func (*ActualLRPKey) ProtoMessage() {}
func (*ActualLRPKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{2}
}
func (m *ActualLRPKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRPKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRPKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRPKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRPKey.Merge(m, src)
}
func (m *ActualLRPKey) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRPKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRPKey.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRPKey proto.InternalMessageInfo

func (m *ActualLRPKey) GetProcessGuid() string {
	if m != nil {
		return m.ProcessGuid
	}
	return ""
}

func (m *ActualLRPKey) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ActualLRPKey) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ActualLRPInstanceKey struct {
	InstanceGuid string `protobuf:"bytes,1,opt,name=instance_guid,json=instanceGuid,proto3" json:"instance_guid"`
	CellId       string `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id"`
}

func (m *ActualLRPInstanceKey) Reset()      { *m = ActualLRPInstanceKey{} }
func (*ActualLRPInstanceKey) ProtoMessage() {}
func (*ActualLRPInstanceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{3}
}
func (m *ActualLRPInstanceKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRPInstanceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRPInstanceKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRPInstanceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRPInstanceKey.Merge(m, src)
}
func (m *ActualLRPInstanceKey) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRPInstanceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRPInstanceKey.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRPInstanceKey proto.InternalMessageInfo

func (m *ActualLRPInstanceKey) GetInstanceGuid() string {
	if m != nil {
		return m.InstanceGuid
	}
	return ""
}

func (m *ActualLRPInstanceKey) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

type ActualLRPNetInfo struct {
	Address           string                            `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	Ports             []*PortMapping                    `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports"`
	InstanceAddress   string                            `protobuf:"bytes,3,opt,name=instance_address,json=instanceAddress,proto3" json:"instance_address,omitempty"`
	PreferredAddress  ActualLRPNetInfo_PreferredAddress `protobuf:"varint,4,opt,name=preferred_address,json=preferredAddress,proto3,enum=models.ActualLRPNetInfo_PreferredAddress" json:"preferred_address"`
	InstanceAddressV6 string                            `protobuf:"bytes,5,opt,name=instance_address_v6,json=instanceAddressV6,proto3" json:"instance_address_v6,omitempty"`
}

func (m *ActualLRPNetInfo) Reset()      { *m = ActualLRPNetInfo{} }
func (*ActualLRPNetInfo) ProtoMessage() {}
func (*ActualLRPNetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{4}
}
func (m *ActualLRPNetInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRPNetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRPNetInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRPNetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRPNetInfo.Merge(m, src)
}
func (m *ActualLRPNetInfo) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRPNetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRPNetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRPNetInfo proto.InternalMessageInfo

func (m *ActualLRPNetInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ActualLRPNetInfo) GetPorts() []*PortMapping {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ActualLRPNetInfo) GetInstanceAddress() string {
	if m != nil {
		return m.InstanceAddress
	}
	return ""
}

func (m *ActualLRPNetInfo) GetPreferredAddress() ActualLRPNetInfo_PreferredAddress {
	if m != nil {
		return m.PreferredAddress
	}
	return ActualLRPNetInfo_PreferredAddressUnknown
}

func (m *ActualLRPNetInfo) GetInstanceAddressV6() string {
	if m != nil {
		return m.InstanceAddressV6
	}
	return ""
}

type ActualLRPInternalRoute struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname"`
}

func (m *ActualLRPInternalRoute) Reset()      { *m = ActualLRPInternalRoute{} }
func (*ActualLRPInternalRoute) ProtoMessage() {}
func (*ActualLRPInternalRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{5}
}
func (m *ActualLRPInternalRoute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRPInternalRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRPInternalRoute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRPInternalRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRPInternalRoute.Merge(m, src)
}
func (m *ActualLRPInternalRoute) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRPInternalRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRPInternalRoute.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRPInternalRoute proto.InternalMessageInfo

func (m *ActualLRPInternalRoute) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type ActualLRP struct {
	ActualLRPKey            `protobuf:"bytes,1,opt,name=actual_lrp_key,json=actualLrpKey,proto3,embedded=actual_lrp_key" json:""`
	ActualLRPInstanceKey    `protobuf:"bytes,2,opt,name=actual_lrp_instance_key,json=actualLrpInstanceKey,proto3,embedded=actual_lrp_instance_key" json:""`
	ActualLRPNetInfo        `protobuf:"bytes,3,opt,name=actual_lrp_net_info,json=actualLrpNetInfo,proto3,embedded=actual_lrp_net_info" json:""`
	CrashCount              int32                     `protobuf:"varint,4,opt,name=crash_count,json=crashCount,proto3" json:"crash_count"`
	CrashReason             string                    `protobuf:"bytes,5,opt,name=crash_reason,json=crashReason,proto3" json:"crash_reason,omitempty"`
	State                   string                    `protobuf:"bytes,6,opt,name=state,proto3" json:"state"`
	PlacementError          string                    `protobuf:"bytes,7,opt,name=placement_error,json=placementError,proto3" json:"placement_error,omitempty"`
	Since                   int64                     `protobuf:"varint,8,opt,name=since,proto3" json:"since"`
	ModificationTag         ModificationTag           `protobuf:"bytes,9,opt,name=modification_tag,json=modificationTag,proto3" json:"modification_tag"`
	Presence                ActualLRP_Presence        `protobuf:"varint,10,opt,name=presence,proto3,enum=models.ActualLRP_Presence" json:"presence"`
	ActualLrpInternalRoutes []*ActualLRPInternalRoute `protobuf:"bytes,11,rep,name=actual_lrp_internal_routes,json=actualLrpInternalRoutes,proto3" json:"actual_lrp_internal_routes,omitempty"`
	MetricTags              map[string]string         `protobuf:"bytes,12,rep,name=metric_tags,json=metricTags,proto3" json:"metric_tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to OptionalRoutable:
	//	*ActualLRP_Routable
	OptionalRoutable isActualLRP_OptionalRoutable `protobuf_oneof:"optional_routable"`
	AvailabilityZone string                       `protobuf:"bytes,14,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone"`
}

func (m *ActualLRP) Reset()      { *m = ActualLRP{} }
func (*ActualLRP) ProtoMessage() {}
func (*ActualLRP) Descriptor() ([]byte, []int) {
	return fileDescriptor_25e5e77bfca46c1a, []int{6}
}
func (m *ActualLRP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActualLRP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActualLRP.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActualLRP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActualLRP.Merge(m, src)
}
func (m *ActualLRP) XXX_Size() int {
	return m.Size()
}
func (m *ActualLRP) XXX_DiscardUnknown() {
	xxx_messageInfo_ActualLRP.DiscardUnknown(m)
}

var xxx_messageInfo_ActualLRP proto.InternalMessageInfo

type isActualLRP_OptionalRoutable interface {
	isActualLRP_OptionalRoutable()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ActualLRP_Routable struct {
	Routable bool `protobuf:"varint,13,opt,name=routable,proto3,oneof" json:"routable"`
}

func (*ActualLRP_Routable) isActualLRP_OptionalRoutable() {}

func (m *ActualLRP) GetOptionalRoutable() isActualLRP_OptionalRoutable {
	if m != nil {
		return m.OptionalRoutable
	}
	return nil
}

func (m *ActualLRP) GetCrashCount() int32 {
	if m != nil {
		return m.CrashCount
	}
	return 0
}

func (m *ActualLRP) GetCrashReason() string {
	if m != nil {
		return m.CrashReason
	}
	return ""
}

func (m *ActualLRP) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ActualLRP) GetPlacementError() string {
	if m != nil {
		return m.PlacementError
	}
	return ""
}

func (m *ActualLRP) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *ActualLRP) GetModificationTag() ModificationTag {
	if m != nil {
		return m.ModificationTag
	}
	return ModificationTag{}
}

func (m *ActualLRP) GetPresence() ActualLRP_Presence {
	if m != nil {
		return m.Presence
	}
	return ActualLRP_Ordinary
}

func (m *ActualLRP) GetActualLrpInternalRoutes() []*ActualLRPInternalRoute {
	if m != nil {
		return m.ActualLrpInternalRoutes
	}
	return nil
}

func (m *ActualLRP) GetMetricTags() map[string]string {
	if m != nil {
		return m.MetricTags
	}
	return nil
}

func (m *ActualLRP) GetRoutable() bool {
	if x, ok := m.GetOptionalRoutable().(*ActualLRP_Routable); ok {
		return x.Routable
	}
	return false
}

func (m *ActualLRP) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ActualLRP) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ActualLRP_Routable)(nil),
	}
}

func init() {
	proto.RegisterEnum("models.ActualLRPNetInfo_PreferredAddress", ActualLRPNetInfo_PreferredAddress_name, ActualLRPNetInfo_PreferredAddress_value)
	proto.RegisterEnum("models.ActualLRP_Presence", ActualLRP_Presence_name, ActualLRP_Presence_value)
	proto.RegisterType((*ActualLRPGroup)(nil), "models.ActualLRPGroup")
	proto.RegisterType((*PortMapping)(nil), "models.PortMapping")
	proto.RegisterType((*ActualLRPKey)(nil), "models.ActualLRPKey")
	proto.RegisterType((*ActualLRPInstanceKey)(nil), "models.ActualLRPInstanceKey")
	proto.RegisterType((*ActualLRPNetInfo)(nil), "models.ActualLRPNetInfo")
	proto.RegisterType((*ActualLRPInternalRoute)(nil), "models.ActualLRPInternalRoute")
	proto.RegisterType((*ActualLRP)(nil), "models.ActualLRP")
	proto.RegisterMapType((map[string]string)(nil), "models.ActualLRP.MetricTagsEntry")
}

func init() { proto.RegisterFile("actual_lrp.proto", fileDescriptor_25e5e77bfca46c1a) }

var fileDescriptor_25e5e77bfca46c1a = []byte{
	// 1219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xed, 0xd8, 0x96, 0x46, 0xb2, 0x4c, 0xaf, 0x9d, 0x98, 0x50, 0x53, 0x52, 0x11, 0x5a,
	0xd4, 0x09, 0x1a, 0xa7, 0x75, 0x82, 0xa0, 0x0d, 0xd0, 0x83, 0xe9, 0xb8, 0xb1, 0x91, 0x44, 0x76,
	0xd7, 0x76, 0x8a, 0xfe, 0x00, 0xec, 0x9a, 0x5a, 0x2b, 0x44, 0x28, 0x2e, 0x41, 0xae, 0xdc, 0xa8,
	0xa7, 0x1e, 0x0b, 0xa3, 0x87, 0x02, 0x3d, 0xfb, 0xde, 0x67, 0xe8, 0x13, 0xe4, 0xe8, 0x63, 0x4e,
	0x44, 0xa3, 0x5c, 0x0a, 0xf6, 0x92, 0x47, 0x28, 0x76, 0xf9, 0x13, 0x9a, 0x4a, 0x4e, 0x3b, 0xfb,
	0xcd, 0xcc, 0x37, 0xb3, 0xb3, 0x33, 0x4b, 0x82, 0x4a, 0x6c, 0x3e, 0x24, 0xae, 0xe5, 0x06, 0xfe,
	0x9a, 0x1f, 0x30, 0xce, 0xd0, 0xec, 0x80, 0xf5, 0xa8, 0x1b, 0xb6, 0x6e, 0xf6, 0x1d, 0xfe, 0x74,
	0x78, 0xb4, 0x66, 0xb3, 0xc1, 0xad, 0x3e, 0xeb, 0xb3, 0x5b, 0x52, 0x7d, 0x34, 0x3c, 0x96, 0x3b,
	0xb9, 0x91, 0x52, 0xe2, 0xd6, 0xba, 0x32, 0x60, 0x3d, 0xe7, 0xd8, 0xb1, 0x09, 0x77, 0x98, 0x67,
	0x71, 0xd2, 0x4f, 0xf0, 0xce, 0x09, 0x34, 0x37, 0x64, 0x88, 0x47, 0x78, 0xef, 0x41, 0xc0, 0x86,
	0x3e, 0xba, 0x09, 0x55, 0xc7, 0x0b, 0x39, 0xf1, 0x6c, 0xaa, 0x29, 0x6d, 0x65, 0xb5, 0xbe, 0xbe,
	0xb8, 0x96, 0xc4, 0x5c, 0xcb, 0x2d, 0x71, 0x6e, 0x82, 0x3e, 0x07, 0xa0, 0x27, 0xc4, 0x1e, 0x12,
	0xee, 0x78, 0x7d, 0x6d, 0xea, 0x7d, 0x0e, 0x05, 0xa3, 0x7b, 0x53, 0x9a, 0xd2, 0xf9, 0x73, 0x0a,
	0xea, 0x7b, 0x2c, 0xe0, 0x8f, 0x89, 0xef, 0x3b, 0x5e, 0x1f, 0x7d, 0x09, 0x4d, 0x9b, 0x79, 0x9c,
	0x38, 0x1e, 0x0d, 0x2c, 0x9f, 0x05, 0x5c, 0xc6, 0x9e, 0x37, 0x51, 0x1c, 0x19, 0x25, 0x0d, 0x9e,
	0xcf, 0xf7, 0x82, 0x01, 0xdd, 0x80, 0xda, 0x53, 0x16, 0xf2, 0xc4, 0x6b, 0x4a, 0x7a, 0xcd, 0xc7,
	0x91, 0xf1, 0x16, 0xc4, 0x55, 0x21, 0x4a, 0xdb, 0x43, 0xd0, 0xde, 0x92, 0x71, 0x37, 0xb4, 0xfc,
	0x80, 0x3d, 0x1f, 0x25, 0xae, 0xd3, 0xd2, 0xf5, 0x6a, 0x1c, 0x19, 0xef, 0xb5, 0xc1, 0x97, 0x73,
	0xcd, 0x81, 0x1b, 0xee, 0x09, 0x5c, 0xd2, 0x7e, 0x0d, 0x4b, 0x32, 0x5a, 0x89, 0xf1, 0x92, 0x64,
	0x5c, 0x89, 0x23, 0xe3, 0x5d, 0x6a, 0xac, 0x0a, 0xb0, 0xc8, 0xd3, 0xf9, 0x4d, 0x81, 0x46, 0x5e,
	0xb3, 0x87, 0x74, 0x84, 0x6e, 0x43, 0xc3, 0x0f, 0x98, 0x4d, 0xc3, 0xd0, 0xea, 0x0f, 0x9d, 0x9e,
	0x2c, 0x4a, 0xcd, 0x54, 0xe3, 0xc8, 0xb8, 0x80, 0xe3, 0x7a, 0xba, 0x7b, 0x30, 0x74, 0x7a, 0xc8,
	0x80, 0x19, 0xc7, 0xeb, 0xd1, 0xe7, 0xb2, 0x18, 0x33, 0x66, 0x2d, 0x8e, 0x8c, 0x04, 0xc0, 0xc9,
	0x82, 0x3a, 0x30, 0xdb, 0x63, 0x03, 0xe2, 0x78, 0xf2, 0xcc, 0x35, 0x13, 0xe2, 0xc8, 0x48, 0x11,
	0x9c, 0xae, 0x1d, 0x0e, 0xcb, 0x79, 0x26, 0x3b, 0xe9, 0x65, 0x8b, 0x8c, 0xee, 0xc2, 0x7c, 0x76,
	0xf7, 0xc5, 0x94, 0x16, 0xe3, 0xc8, 0xb8, 0xa8, 0xc0, 0x8d, 0x6c, 0x2b, 0x93, 0xfa, 0x08, 0xe6,
	0x6c, 0xea, 0xba, 0x96, 0xd3, 0x93, 0x69, 0xd5, 0xcc, 0x7a, 0x1c, 0x19, 0x19, 0x84, 0x67, 0x85,
	0xb0, 0xd3, 0xeb, 0xfc, 0x37, 0x0d, 0x6a, 0x1e, 0xb6, 0x4b, 0xf9, 0x8e, 0x77, 0xcc, 0xd0, 0xc7,
	0x30, 0x47, 0x7a, 0xbd, 0x80, 0x86, 0x61, 0x1a, 0x4c, 0xba, 0xa6, 0x10, 0xce, 0x04, 0x74, 0x07,
	0x66, 0x44, 0x59, 0x43, 0x6d, 0xaa, 0x3d, 0xbd, 0x5a, 0x5f, 0x5f, 0xca, 0x9a, 0xb0, 0xd0, 0x66,
	0x49, 0x2d, 0xa4, 0x15, 0x4e, 0x16, 0x74, 0x1d, 0xd4, 0x3c, 0xed, 0x2c, 0x8a, 0xac, 0x0a, 0x5e,
	0xc8, 0xf0, 0x8d, 0x34, 0xc0, 0x00, 0x16, 0xfd, 0x80, 0x1e, 0xd3, 0x20, 0xa0, 0xbd, 0xdc, 0x56,
	0xdc, 0x71, 0x73, 0xfd, 0xfa, 0x44, 0xc7, 0xa7, 0xc9, 0xaf, 0xed, 0x65, 0x1e, 0x29, 0x8b, 0x79,
	0x39, 0x8e, 0x8c, 0x49, 0x1e, 0xac, 0xfa, 0x25, 0x43, 0xf4, 0x0d, 0x2c, 0x95, 0x33, 0xb3, 0x4e,
	0xee, 0x6a, 0x33, 0xb2, 0x04, 0xd7, 0xe2, 0xc8, 0xf8, 0xf0, 0x1d, 0xea, 0x4f, 0xd9, 0xc0, 0xe1,
	0x74, 0xe0, 0xf3, 0x11, 0x5e, 0x2c, 0xe5, 0xff, 0xe4, 0x6e, 0xe7, 0x77, 0x05, 0xd4, 0x72, 0x42,
	0x68, 0x15, 0xe6, 0x0e, 0xbb, 0x0f, 0xbb, 0xbb, 0xdf, 0x76, 0xd5, 0x4a, 0xeb, 0x83, 0xd3, 0xb3,
	0xf6, 0x4a, 0xd9, 0xe4, 0xd0, 0x7b, 0xe6, 0xb1, 0x9f, 0x3d, 0x74, 0x03, 0xaa, 0x3b, 0xdd, 0xfd,
	0x83, 0x8d, 0xee, 0xe6, 0x96, 0xaa, 0xb4, 0xae, 0x9e, 0x9e, 0xb5, 0xb5, 0xb2, 0x69, 0xd6, 0x2a,
	0xa8, 0x03, 0x97, 0xb6, 0x77, 0xf7, 0x0f, 0xd4, 0xa9, 0x96, 0x76, 0x7a, 0xd6, 0x5e, 0x2e, 0xdb,
	0x6d, 0xb3, 0x90, 0x77, 0x4c, 0xb8, 0x52, 0xe8, 0x31, 0x4e, 0x03, 0x8f, 0xb8, 0x98, 0x0d, 0x39,
	0x45, 0xab, 0x20, 0x67, 0xd6, 0x23, 0x03, 0x9a, 0xde, 0x79, 0x23, 0x8e, 0x8c, 0x1c, 0xc3, 0xb9,
	0xd4, 0xf9, 0xbb, 0x0a, 0xb5, 0x9c, 0x04, 0x6d, 0x43, 0xf3, 0xed, 0x8b, 0x69, 0x3d, 0xa3, 0xa3,
	0xf4, 0x09, 0x5b, 0x9e, 0xb8, 0x9f, 0x87, 0x74, 0x64, 0x36, 0x5e, 0x44, 0x46, 0xe5, 0x3c, 0x32,
	0x94, 0x38, 0x32, 0x2a, 0xb8, 0x91, 0x78, 0x3e, 0x0a, 0x7c, 0xd1, 0xe7, 0x04, 0x56, 0x0a, 0x4c,
	0x79, 0xa5, 0x05, 0x65, 0xf2, 0xc8, 0x5d, 0x9d, 0xa0, 0x2c, 0x8c, 0x49, 0x89, 0x7a, 0x39, 0xa7,
	0x2e, 0x8e, 0xd2, 0x21, 0x2c, 0x15, 0x42, 0x78, 0x94, 0x5b, 0x8e, 0x77, 0xcc, 0x64, 0xf7, 0xd5,
	0xd7, 0xb5, 0xf7, 0x75, 0x54, 0x89, 0x5a, 0xcd, 0xa9, 0xb3, 0x71, 0xf9, 0x0c, 0xea, 0x76, 0x40,
	0xc2, 0xa7, 0x96, 0xcd, 0x86, 0x5e, 0xf2, 0x08, 0xcd, 0x98, 0x0b, 0x71, 0x64, 0x14, 0x61, 0x0c,
	0x72, 0xb3, 0x29, 0x64, 0x74, 0x0d, 0x1a, 0x89, 0x2a, 0xa0, 0x24, 0x64, 0x5e, 0xd2, 0x62, 0x38,
	0x31, 0xc7, 0x12, 0x12, 0x6f, 0x4a, 0xc8, 0x09, 0xa7, 0xda, 0xac, 0xbc, 0x0d, 0x39, 0x47, 0x12,
	0xc0, 0xc9, 0x82, 0x3e, 0x81, 0x05, 0xdf, 0x25, 0x36, 0x1d, 0x50, 0x8f, 0x5b, 0x34, 0x08, 0x58,
	0xa0, 0xcd, 0x49, 0x9a, 0x66, 0x0e, 0x6f, 0x09, 0x54, 0x32, 0x39, 0xe2, 0xe3, 0x52, 0x6d, 0x2b,
	0xab, 0xd3, 0x29, 0x93, 0x00, 0x70, 0xb2, 0xa0, 0x1f, 0x41, 0x2d, 0x7f, 0xac, 0xb4, 0x9a, 0xac,
	0xc9, 0x4a, 0x56, 0x93, 0xc7, 0x05, 0xfd, 0x01, 0xe9, 0x9b, 0x9a, 0x28, 0x49, 0x1c, 0x19, 0x13,
	0x8e, 0x78, 0x61, 0x70, 0xd1, 0x14, 0xdd, 0x87, 0xaa, 0x1f, 0xd0, 0x90, 0x8a, 0x0c, 0x40, 0xce,
	0x6e, 0x6b, 0xa2, 0xd2, 0x62, 0x68, 0xa5, 0x45, 0xd2, 0x75, 0x99, 0x3d, 0xce, 0x25, 0xf4, 0x03,
	0xb4, 0x2e, 0x74, 0x47, 0xd2, 0xbb, 0x56, 0x20, 0x9a, 0x37, 0xd4, 0xea, 0xf2, 0x01, 0xd2, 0xdf,
	0xd1, 0x20, 0x85, 0x1e, 0xc7, 0x2b, 0x85, 0xa6, 0x28, 0xe0, 0x21, 0x32, 0xa1, 0x3e, 0xa0, 0x3c,
	0x70, 0x6c, 0x71, 0x82, 0x50, 0x6b, 0x48, 0xb6, 0x6b, 0x93, 0x59, 0x3e, 0x96, 0x46, 0x07, 0xa4,
	0x1f, 0x6e, 0x79, 0x3c, 0x18, 0x61, 0x18, 0xe4, 0x80, 0x18, 0x55, 0x91, 0x0c, 0x39, 0x72, 0xa9,
	0x36, 0xdf, 0x56, 0x56, 0xab, 0xc9, 0x51, 0x32, 0x6c, 0xbb, 0x82, 0x73, 0x19, 0x99, 0xb0, 0x48,
	0x4e, 0x88, 0xe3, 0x92, 0x23, 0xc7, 0x75, 0xf8, 0xc8, 0xfa, 0x85, 0x79, 0x54, 0x6b, 0xca, 0x7b,
	0x96, 0x8f, 0xd5, 0x84, 0x12, 0xab, 0x45, 0xe8, 0x7b, 0xe6, 0xd1, 0xd6, 0x57, 0xb0, 0x50, 0x4a,
	0x07, 0xa9, 0x30, 0x9d, 0x0d, 0x60, 0x0d, 0x0b, 0x11, 0x2d, 0xc3, 0xcc, 0x09, 0x71, 0x87, 0x34,
	0xf9, 0x02, 0xe0, 0x64, 0x73, 0x6f, 0xea, 0x0b, 0xa5, 0xf3, 0x13, 0x54, 0xb3, 0x9a, 0xa3, 0x16,
	0x54, 0x77, 0xf1, 0xfd, 0x9d, 0xee, 0x06, 0xfe, 0x4e, 0xad, 0xb4, 0x1a, 0xa7, 0x67, 0xed, 0xea,
	0x6e, 0xd0, 0x73, 0x3c, 0x12, 0x8c, 0x90, 0x0e, 0xb0, 0xf5, 0x64, 0x63, 0xf3, 0x70, 0xe3, 0x60,
	0xa7, 0xfb, 0x40, 0x55, 0x5a, 0xcd, 0xd3, 0xb3, 0x36, 0x6c, 0xe5, 0xbf, 0x16, 0x48, 0x83, 0xb9,
	0xfd, 0xc3, 0xfd, 0xbd, 0xad, 0x4d, 0xf1, 0xf0, 0xd4, 0x4f, 0xcf, 0xda, 0x73, 0xfb, 0xc3, 0xd0,
	0xa7, 0x36, 0x37, 0x97, 0x60, 0x91, 0xf9, 0xa2, 0x09, 0xd2, 0x6b, 0x12, 0x27, 0x37, 0xef, 0x9c,
	0xbf, 0xd2, 0x95, 0x97, 0xaf, 0xf4, 0xca, 0x9b, 0x57, 0xba, 0xf2, 0xeb, 0x58, 0x57, 0xfe, 0x1a,
	0xeb, 0xca, 0x8b, 0xb1, 0xae, 0x9c, 0x8f, 0x75, 0xe5, 0x9f, 0xb1, 0xae, 0xfc, 0x3b, 0xd6, 0x2b,
	0x6f, 0xc6, 0xba, 0xf2, 0xc7, 0x6b, 0xbd, 0x72, 0xfe, 0x5a, 0xaf, 0xbc, 0x7c, 0xad, 0x57, 0x8e,
	0x66, 0xe5, 0xaf, 0xd3, 0xed, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x75, 0xbb, 0xcc, 0x68, 0x9d,
	0x09, 0x00, 0x00,
}

func (x ActualLRPNetInfo_PreferredAddress) String() string {
	s, ok := ActualLRPNetInfo_PreferredAddress_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ActualLRP_Presence) String() string {
	s, ok := ActualLRP_Presence_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *ActualLRPGroup) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRPGroup)
	if !ok {
		that2, ok := that.(ActualLRPGroup)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Instance.Equal(that1.Instance) {
		return false
	}
	if !this.Evacuating.Equal(that1.Evacuating) {
		return false
	}
	return true
}
func (this *PortMapping) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PortMapping)
	if !ok {
		that2, ok := that.(PortMapping)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ContainerPort != that1.ContainerPort {
		return false
	}
	if this.HostPort != that1.HostPort {
		return false
	}
	if this.ContainerTlsProxyPort != that1.ContainerTlsProxyPort {
		return false
	}
	if this.HostTlsProxyPort != that1.HostTlsProxyPort {
		return false
	}
	return true
}
func (this *ActualLRPKey) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRPKey)
	if !ok {
		that2, ok := that.(ActualLRPKey)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ProcessGuid != that1.ProcessGuid {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	return true
}
func (this *ActualLRPInstanceKey) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRPInstanceKey)
	if !ok {
		that2, ok := that.(ActualLRPInstanceKey)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.InstanceGuid != that1.InstanceGuid {
		return false
	}
	if this.CellId != that1.CellId {
		return false
	}
	return true
}
func (this *ActualLRPNetInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRPNetInfo)
	if !ok {
		that2, ok := that.(ActualLRPNetInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if len(this.Ports) != len(that1.Ports) {
		return false
	}
	for i := range this.Ports {
		if !this.Ports[i].Equal(that1.Ports[i]) {
			return false
		}
	}
	if this.InstanceAddress != that1.InstanceAddress {
		return false
	}
	if this.PreferredAddress != that1.PreferredAddress {
		return false
	}
	if this.InstanceAddressV6 != that1.InstanceAddressV6 {
		return false
	}
	return true
}
func (this *ActualLRPInternalRoute) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRPInternalRoute)
	if !ok {
		that2, ok := that.(ActualLRPInternalRoute)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	return true
}
func (this *ActualLRP) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRP)
	if !ok {
		that2, ok := that.(ActualLRP)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ActualLRPKey.Equal(&that1.ActualLRPKey) {
		return false
	}
	if !this.ActualLRPInstanceKey.Equal(&that1.ActualLRPInstanceKey) {
		return false
	}
	if !this.ActualLRPNetInfo.Equal(&that1.ActualLRPNetInfo) {
		return false
	}
	if this.CrashCount != that1.CrashCount {
		return false
	}
	if this.CrashReason != that1.CrashReason {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if this.PlacementError != that1.PlacementError {
		return false
	}
	if this.Since != that1.Since {
		return false
	}
	if !this.ModificationTag.Equal(&that1.ModificationTag) {
		return false
	}
	if this.Presence != that1.Presence {
		return false
	}
	if len(this.ActualLrpInternalRoutes) != len(that1.ActualLrpInternalRoutes) {
		return false
	}
	for i := range this.ActualLrpInternalRoutes {
		if !this.ActualLrpInternalRoutes[i].Equal(that1.ActualLrpInternalRoutes[i]) {
			return false
		}
	}
	if len(this.MetricTags) != len(that1.MetricTags) {
		return false
	}
	for i := range this.MetricTags {
		if this.MetricTags[i] != that1.MetricTags[i] {
			return false
		}
	}
	if that1.OptionalRoutable == nil {
		if this.OptionalRoutable != nil {
			return false
		}
	} else if this.OptionalRoutable == nil {
		return false
	} else if !this.OptionalRoutable.Equal(that1.OptionalRoutable) {
		return false
	}
	if this.AvailabilityZone != that1.AvailabilityZone {
		return false
	}
	return true
}
func (this *ActualLRP_Routable) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActualLRP_Routable)
	if !ok {
		that2, ok := that.(ActualLRP_Routable)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Routable != that1.Routable {
		return false
	}
	return true
}
func (this *ActualLRPGroup) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&models.ActualLRPGroup{")
	if this.Instance != nil {
		s = append(s, "Instance: "+fmt.Sprintf("%#v", this.Instance)+",\n")
	}
	if this.Evacuating != nil {
		s = append(s, "Evacuating: "+fmt.Sprintf("%#v", this.Evacuating)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PortMapping) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&models.PortMapping{")
	s = append(s, "ContainerPort: "+fmt.Sprintf("%#v", this.ContainerPort)+",\n")
	s = append(s, "HostPort: "+fmt.Sprintf("%#v", this.HostPort)+",\n")
	s = append(s, "ContainerTlsProxyPort: "+fmt.Sprintf("%#v", this.ContainerTlsProxyPort)+",\n")
	s = append(s, "HostTlsProxyPort: "+fmt.Sprintf("%#v", this.HostTlsProxyPort)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRPKey) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&models.ActualLRPKey{")
	s = append(s, "ProcessGuid: "+fmt.Sprintf("%#v", this.ProcessGuid)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRPInstanceKey) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&models.ActualLRPInstanceKey{")
	s = append(s, "InstanceGuid: "+fmt.Sprintf("%#v", this.InstanceGuid)+",\n")
	s = append(s, "CellId: "+fmt.Sprintf("%#v", this.CellId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRPNetInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&models.ActualLRPNetInfo{")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	if this.Ports != nil {
		s = append(s, "Ports: "+fmt.Sprintf("%#v", this.Ports)+",\n")
	}
	s = append(s, "InstanceAddress: "+fmt.Sprintf("%#v", this.InstanceAddress)+",\n")
	s = append(s, "PreferredAddress: "+fmt.Sprintf("%#v", this.PreferredAddress)+",\n")
	s = append(s, "InstanceAddressV6: "+fmt.Sprintf("%#v", this.InstanceAddressV6)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRPInternalRoute) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&models.ActualLRPInternalRoute{")
	s = append(s, "Hostname: "+fmt.Sprintf("%#v", this.Hostname)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRP) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 18)
	s = append(s, "&models.ActualLRP{")
	s = append(s, "ActualLRPKey: "+strings.Replace(this.ActualLRPKey.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "ActualLRPInstanceKey: "+strings.Replace(this.ActualLRPInstanceKey.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "ActualLRPNetInfo: "+strings.Replace(this.ActualLRPNetInfo.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "CrashCount: "+fmt.Sprintf("%#v", this.CrashCount)+",\n")
	s = append(s, "CrashReason: "+fmt.Sprintf("%#v", this.CrashReason)+",\n")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "PlacementError: "+fmt.Sprintf("%#v", this.PlacementError)+",\n")
	s = append(s, "Since: "+fmt.Sprintf("%#v", this.Since)+",\n")
	s = append(s, "ModificationTag: "+strings.Replace(this.ModificationTag.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "Presence: "+fmt.Sprintf("%#v", this.Presence)+",\n")
	if this.ActualLrpInternalRoutes != nil {
		s = append(s, "ActualLrpInternalRoutes: "+fmt.Sprintf("%#v", this.ActualLrpInternalRoutes)+",\n")
	}
	keysForMetricTags := make([]string, 0, len(this.MetricTags))
	for k, _ := range this.MetricTags {
		keysForMetricTags = append(keysForMetricTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForMetricTags)
	mapStringForMetricTags := "map[string]string{"
	for _, k := range keysForMetricTags {
		mapStringForMetricTags += fmt.Sprintf("%#v: %#v,", k, this.MetricTags[k])
	}
	mapStringForMetricTags += "}"
	if this.MetricTags != nil {
		s = append(s, "MetricTags: "+mapStringForMetricTags+",\n")
	}
	if this.OptionalRoutable != nil {
		s = append(s, "OptionalRoutable: "+fmt.Sprintf("%#v", this.OptionalRoutable)+",\n")
	}
	s = append(s, "AvailabilityZone: "+fmt.Sprintf("%#v", this.AvailabilityZone)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActualLRP_Routable) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&models.ActualLRP_Routable{` +
		`Routable:` + fmt.Sprintf("%#v", this.Routable) + `}`}, ", ")
	return s
}
func valueToGoStringActualLrp(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ActualLRPGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRPGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRPGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Evacuating != nil {
		{
			size, err := m.Evacuating.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintActualLrp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Instance != nil {
		{
			size, err := m.Instance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintActualLrp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PortMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PortMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PortMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HostTlsProxyPort != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.HostTlsProxyPort))
		i--
		dAtA[i] = 0x20
	}
	if m.ContainerTlsProxyPort != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.ContainerTlsProxyPort))
		i--
		dAtA[i] = 0x18
	}
	if m.HostPort != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.HostPort))
		i--
		dAtA[i] = 0x10
	}
	if m.ContainerPort != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.ContainerPort))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActualLRPKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRPKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRPKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ProcessGuid) > 0 {
		i -= len(m.ProcessGuid)
		copy(dAtA[i:], m.ProcessGuid)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.ProcessGuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActualLRPInstanceKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRPInstanceKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRPInstanceKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CellId) > 0 {
		i -= len(m.CellId)
		copy(dAtA[i:], m.CellId)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.CellId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.InstanceGuid) > 0 {
		i -= len(m.InstanceGuid)
		copy(dAtA[i:], m.InstanceGuid)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.InstanceGuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActualLRPNetInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRPNetInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRPNetInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InstanceAddressV6) > 0 {
		i -= len(m.InstanceAddressV6)
		copy(dAtA[i:], m.InstanceAddressV6)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.InstanceAddressV6)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PreferredAddress != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.PreferredAddress))
		i--
		dAtA[i] = 0x20
	}
	if len(m.InstanceAddress) > 0 {
		i -= len(m.InstanceAddress)
		copy(dAtA[i:], m.InstanceAddress)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.InstanceAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ports) > 0 {
		for iNdEx := len(m.Ports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActualLrp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActualLRPInternalRoute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRPInternalRoute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRPInternalRoute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hostname) > 0 {
		i -= len(m.Hostname)
		copy(dAtA[i:], m.Hostname)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.Hostname)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActualLRP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActualLRP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AvailabilityZone) > 0 {
		i -= len(m.AvailabilityZone)
		copy(dAtA[i:], m.AvailabilityZone)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.AvailabilityZone)))
		i--
		dAtA[i] = 0x72
	}
	if m.OptionalRoutable != nil {
		{
			size := m.OptionalRoutable.Size()
			i -= size
			if _, err := m.OptionalRoutable.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.MetricTags) > 0 {
		for k := range m.MetricTags {
			v := m.MetricTags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintActualLrp(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintActualLrp(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintActualLrp(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.ActualLrpInternalRoutes) > 0 {
		for iNdEx := len(m.ActualLrpInternalRoutes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActualLrpInternalRoutes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActualLrp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.Presence != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.Presence))
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.ModificationTag.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintActualLrp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.Since != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.Since))
		i--
		dAtA[i] = 0x40
	}
	if len(m.PlacementError) > 0 {
		i -= len(m.PlacementError)
		copy(dAtA[i:], m.PlacementError)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.PlacementError)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CrashReason) > 0 {
		i -= len(m.CrashReason)
		copy(dAtA[i:], m.CrashReason)
		i = encodeVarintActualLrp(dAtA, i, uint64(len(m.CrashReason)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CrashCount != 0 {
		i = encodeVarintActualLrp(dAtA, i, uint64(m.CrashCount))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.ActualLRPNetInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintActualLrp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ActualLRPInstanceKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintActualLrp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ActualLRPKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintActualLrp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ActualLRP_Routable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActualLRP_Routable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i--
	if m.Routable {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x68
	return len(dAtA) - i, nil
}
func encodeVarintActualLrp(dAtA []byte, offset int, v uint64) int {
	offset -= sovActualLrp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ActualLRPGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Instance != nil {
		l = m.Instance.Size()
		n += 1 + l + sovActualLrp(uint64(l))
	}
	if m.Evacuating != nil {
		l = m.Evacuating.Size()
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *PortMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ContainerPort != 0 {
		n += 1 + sovActualLrp(uint64(m.ContainerPort))
	}
	if m.HostPort != 0 {
		n += 1 + sovActualLrp(uint64(m.HostPort))
	}
	if m.ContainerTlsProxyPort != 0 {
		n += 1 + sovActualLrp(uint64(m.ContainerTlsProxyPort))
	}
	if m.HostTlsProxyPort != 0 {
		n += 1 + sovActualLrp(uint64(m.HostTlsProxyPort))
	}
	return n
}

func (m *ActualLRPKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProcessGuid)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovActualLrp(uint64(m.Index))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *ActualLRPInstanceKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InstanceGuid)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	l = len(m.CellId)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *ActualLRPNetInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	if len(m.Ports) > 0 {
		for _, e := range m.Ports {
			l = e.Size()
			n += 1 + l + sovActualLrp(uint64(l))
		}
	}
	l = len(m.InstanceAddress)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	if m.PreferredAddress != 0 {
		n += 1 + sovActualLrp(uint64(m.PreferredAddress))
	}
	l = len(m.InstanceAddressV6)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *ActualLRPInternalRoute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *ActualLRP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ActualLRPKey.Size()
	n += 1 + l + sovActualLrp(uint64(l))
	l = m.ActualLRPInstanceKey.Size()
	n += 1 + l + sovActualLrp(uint64(l))
	l = m.ActualLRPNetInfo.Size()
	n += 1 + l + sovActualLrp(uint64(l))
	if m.CrashCount != 0 {
		n += 1 + sovActualLrp(uint64(m.CrashCount))
	}
	l = len(m.CrashReason)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	l = len(m.PlacementError)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	if m.Since != 0 {
		n += 1 + sovActualLrp(uint64(m.Since))
	}
	l = m.ModificationTag.Size()
	n += 1 + l + sovActualLrp(uint64(l))
	if m.Presence != 0 {
		n += 1 + sovActualLrp(uint64(m.Presence))
	}
	if len(m.ActualLrpInternalRoutes) > 0 {
		for _, e := range m.ActualLrpInternalRoutes {
			l = e.Size()
			n += 1 + l + sovActualLrp(uint64(l))
		}
	}
	if len(m.MetricTags) > 0 {
		for k, v := range m.MetricTags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovActualLrp(uint64(len(k))) + 1 + len(v) + sovActualLrp(uint64(len(v)))
			n += mapEntrySize + 1 + sovActualLrp(uint64(mapEntrySize))
		}
	}
	if m.OptionalRoutable != nil {
		n += m.OptionalRoutable.Size()
	}
	l = len(m.AvailabilityZone)
	if l > 0 {
		n += 1 + l + sovActualLrp(uint64(l))
	}
	return n
}

func (m *ActualLRP_Routable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	return n
}

func sovActualLrp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActualLrp(x uint64) (n int) {
	return sovActualLrp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ActualLRPGroup) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActualLRPGroup{`,
		`Instance:` + strings.Replace(this.Instance.String(), "ActualLRP", "ActualLRP", 1) + `,`,
		`Evacuating:` + strings.Replace(this.Evacuating.String(), "ActualLRP", "ActualLRP", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PortMapping) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PortMapping{`,
		`ContainerPort:` + fmt.Sprintf("%v", this.ContainerPort) + `,`,
		`HostPort:` + fmt.Sprintf("%v", this.HostPort) + `,`,
		`ContainerTlsProxyPort:` + fmt.Sprintf("%v", this.ContainerTlsProxyPort) + `,`,
		`HostTlsProxyPort:` + fmt.Sprintf("%v", this.HostTlsProxyPort) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRPKey) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActualLRPKey{`,
		`ProcessGuid:` + fmt.Sprintf("%v", this.ProcessGuid) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRPInstanceKey) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActualLRPInstanceKey{`,
		`InstanceGuid:` + fmt.Sprintf("%v", this.InstanceGuid) + `,`,
		`CellId:` + fmt.Sprintf("%v", this.CellId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRPNetInfo) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPorts := "[]*PortMapping{"
	for _, f := range this.Ports {
		repeatedStringForPorts += strings.Replace(f.String(), "PortMapping", "PortMapping", 1) + ","
	}
	repeatedStringForPorts += "}"
	s := strings.Join([]string{`&ActualLRPNetInfo{`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`Ports:` + repeatedStringForPorts + `,`,
		`InstanceAddress:` + fmt.Sprintf("%v", this.InstanceAddress) + `,`,
		`PreferredAddress:` + fmt.Sprintf("%v", this.PreferredAddress) + `,`,
		`InstanceAddressV6:` + fmt.Sprintf("%v", this.InstanceAddressV6) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRPInternalRoute) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActualLRPInternalRoute{`,
		`Hostname:` + fmt.Sprintf("%v", this.Hostname) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRP) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForActualLrpInternalRoutes := "[]*ActualLRPInternalRoute{"
	for _, f := range this.ActualLrpInternalRoutes {
		repeatedStringForActualLrpInternalRoutes += strings.Replace(f.String(), "ActualLRPInternalRoute", "ActualLRPInternalRoute", 1) + ","
	}
	repeatedStringForActualLrpInternalRoutes += "}"
	keysForMetricTags := make([]string, 0, len(this.MetricTags))
	for k, _ := range this.MetricTags {
		keysForMetricTags = append(keysForMetricTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForMetricTags)
	mapStringForMetricTags := "map[string]string{"
	for _, k := range keysForMetricTags {
		mapStringForMetricTags += fmt.Sprintf("%v: %v,", k, this.MetricTags[k])
	}
	mapStringForMetricTags += "}"
	s := strings.Join([]string{`&ActualLRP{`,
		`ActualLRPKey:` + strings.Replace(strings.Replace(this.ActualLRPKey.String(), "ActualLRPKey", "ActualLRPKey", 1), `&`, ``, 1) + `,`,
		`ActualLRPInstanceKey:` + strings.Replace(strings.Replace(this.ActualLRPInstanceKey.String(), "ActualLRPInstanceKey", "ActualLRPInstanceKey", 1), `&`, ``, 1) + `,`,
		`ActualLRPNetInfo:` + strings.Replace(strings.Replace(this.ActualLRPNetInfo.String(), "ActualLRPNetInfo", "ActualLRPNetInfo", 1), `&`, ``, 1) + `,`,
		`CrashCount:` + fmt.Sprintf("%v", this.CrashCount) + `,`,
		`CrashReason:` + fmt.Sprintf("%v", this.CrashReason) + `,`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`PlacementError:` + fmt.Sprintf("%v", this.PlacementError) + `,`,
		`Since:` + fmt.Sprintf("%v", this.Since) + `,`,
		`ModificationTag:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ModificationTag), "ModificationTag", "ModificationTag", 1), `&`, ``, 1) + `,`,
		`Presence:` + fmt.Sprintf("%v", this.Presence) + `,`,
		`ActualLrpInternalRoutes:` + repeatedStringForActualLrpInternalRoutes + `,`,
		`MetricTags:` + mapStringForMetricTags + `,`,
		`OptionalRoutable:` + fmt.Sprintf("%v", this.OptionalRoutable) + `,`,
		`AvailabilityZone:` + fmt.Sprintf("%v", this.AvailabilityZone) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActualLRP_Routable) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActualLRP_Routable{`,
		`Routable:` + fmt.Sprintf("%v", this.Routable) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringActualLrp(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ActualLRPGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRPGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRPGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Instance == nil {
				m.Instance = &ActualLRP{}
			}
			if err := m.Instance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evacuating", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evacuating == nil {
				m.Evacuating = &ActualLRP{}
			}
			if err := m.Evacuating.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PortMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PortMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PortMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerPort", wireType)
			}
			m.ContainerPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContainerPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostPort", wireType)
			}
			m.HostPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HostPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerTlsProxyPort", wireType)
			}
			m.ContainerTlsProxyPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContainerTlsProxyPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostTlsProxyPort", wireType)
			}
			m.HostTlsProxyPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HostTlsProxyPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActualLRPKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRPKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRPKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessGuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessGuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActualLRPInstanceKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRPInstanceKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRPInstanceKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceGuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceGuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CellId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CellId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActualLRPNetInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRPNetInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRPNetInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ports = append(m.Ports, &PortMapping{})
			if err := m.Ports[len(m.Ports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredAddress", wireType)
			}
			m.PreferredAddress = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreferredAddress |= ActualLRPNetInfo_PreferredAddress(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceAddressV6", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceAddressV6 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActualLRPInternalRoute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRPInternalRoute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRPInternalRoute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActualLRP) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActualLRP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActualLRP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualLRPKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActualLRPKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualLRPInstanceKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActualLRPInstanceKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualLRPNetInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActualLRPNetInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrashCount", wireType)
			}
			m.CrashCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CrashCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrashReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CrashReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlacementError", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlacementError = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Since", wireType)
			}
			m.Since = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Since |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModificationTag", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModificationTag.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Presence", wireType)
			}
			m.Presence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Presence |= ActualLRP_Presence(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualLrpInternalRoutes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActualLrpInternalRoutes = append(m.ActualLrpInternalRoutes, &ActualLRPInternalRoute{})
			if err := m.ActualLrpInternalRoutes[len(m.ActualLrpInternalRoutes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricTags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MetricTags == nil {
				m.MetricTags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowActualLrp
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowActualLrp
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthActualLrp
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthActualLrp
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowActualLrp
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthActualLrp
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthActualLrp
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipActualLrp(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthActualLrp
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.MetricTags[mapkey] = mapvalue
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Routable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.OptionalRoutable = &ActualLRP_Routable{b}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailabilityZone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActualLrp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActualLrp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailabilityZone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActualLrp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActualLrp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActualLrp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActualLrp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActualLrp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActualLrp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActualLrp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActualLrp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActualLrp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActualLrp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActualLrp = fmt.Errorf("proto: unexpected end of group")
)
